### ISSUE TITLE
Daily reminders?

### ISSUE THREAD

**Issue by chamik** [scp-cs/Thorn#19]
Daily reminders are awesome, and they've been requested by the community for quite a long while. The problem is that they are incredibly boring to prepare and write down. @HEG1 and myself have tried, but neither of us has lasted very long. Having to deploy the bot again after every reminder update is also a huge pain in the ass.

Having said that, I've come up with three possible solutions to this problem.

**1. The lazy solution: Just give up**
Ditch reminders. To be honest, I am not a fan of this, but they are just painful to deal with.

**2. The more lazy solution: Crowdsource**
aka make other people do the work I am too lazy to do.

**3. The 'smart'-but-requires-effort solution:**
Make a script that fetches data from [Wikidata](https://www.wikidata.org/wiki/Wikidata:Main_Page), lists each event for a given day, gives the user option to delete non-interesting items, format the rest and repeat.

I really like the option 3, I'm just looking for an excuse not to do it.

**Comment by HEG1** [comment]
We might as well ask the community if sb would like to take part in this and give them the option of chickening out whenever they'd want. If let's say 10 ppl added like 2-3 days then it's plenty. I think it wouldn't be a bad idea to "bind" the community together a little through this. 

But yeah, the third one souds cool.

**Comment by chamik** [comment]
solved in #121 <3
