### ISSUE TITLE
Remove the auto-reaction from quick links?

### ISSUE THREAD

**Issue by chamik** [scp-cs/Thorn#21]
It just feels unnecessary, I guess. The auto-reaction can feel confusing to new users, and it takes up precious space on the screen. The functionality would stay the same (the message will get deleted when someone reacts with the newspapers emoji), just the auto-reaction would disappear.

Looking for thoughts on this one.

**Comment by HEG1** [comment]
Agree. It has come to a point, where it sends the message mostly when actually needed. And if needed be then finding that newspaper in reaction takes lika a second or so. 

But I think it would be a good idea to let the community decide. They are the ones using it.

**Comment by Aidam7** [comment]
I mean, the auto react is pretty much common knowledge that the newspapers will delete the message so there's no point in having it automatically pop up, but at the same time I don't see a need to remove it.

As @HEG1 said I would just let the Community decide.

**Comment by chamik** [comment]
Given that it seems I am the only person this thing bothers, we'll leave it as is.
