### ISSUE TITLE
Add Slash Commands

### ISSUE THREAD

**Issue by chamik** [scp-cs/Thorn#23]
As Discord puts it: "Slash Commands are the new, exciting way to build and interact with apps on Discord."

I should probably get on the hype train already.

**Comment by chamik** [comment]
i don't think this is really needed/wanted? @Aidam7 @x10102 pls thoughts

**Comment by Aidam7** [comment]
Yeah, I don't think we need to implement them, not like we're gonna reach the point where they become mandatory for us to use them anytime soon, close away
