### ISSUE TITLE
Auto deploy to server

### ISSUE THREAD

**Issue by chamik** [scp-cs/Thorn#26]
Having to manually deploy the bot after any change is getting rigorous. Time to automate stuff.

**Comment by chamik** [comment]
I'm going to leave this open for a while to see If it actually works. Hopefully it does.

**Comment by chamik** [comment]
Turns out it doesn't :/

**Comment by Aidam7** [comment]
> Turns out it doesn't :/

Back to the drawing board...

**Comment by chamik** [comment]
Turns out this is more difficult then I thought. I'll completely remove it for now and get back to it someday later.

**Comment by chamik** [comment]
i will NEVER touch this again i swear to god
