### ISSUE TITLE
Not posting newly created pages

### ISSUE THREAD

**Issue by chamik** [scp-cs/Thorn#32]
It's been an issue for a while now. It just suddenly stopped working, no idea why. I'm going to look into this.

**Comment by chamik** [comment]
Turns out it's just a config issue? lol. Someone (@ModularEntree :eyes:) has been translating Wikidot to Czech and changed a string I used for the filtering.

**Comment by Aidam7** [comment]
Turns out @ModularEntree can be too active for his own good
